name: 📝 Documentation
description: Improve or update documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs attention?
      options:
        - README
        - User Guide
        - Contributing Guide
        - Architecture Documentation
        - Code Comments
        - API Documentation
        - Setup/Installation Guide
        - Other
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Documentation Issue
      description: What's unclear, missing, or incorrect in the current documentation?
      placeholder: Describe the documentation issue...
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is this documentation located?
      placeholder: |
        File: docs/USER_GUIDE.md
        Section: "Using Clinical Scores"
    validations:
      required: false

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should we improve this documentation?
      placeholder: Describe your suggested changes...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context or examples
    validations:
      required: false
